# Generated by Django 4.1.5 on 2023-02-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
